INSERT INTO Client (nom_client, prenom_client, telephone_client, mail_client, mdp_client) VALUES ('Dupont', 'Jean', '0102030405', 'dupontjean@client.fr', 'test');
INSERT INTO Client (nom_client, prenom_client, telephone_client, mail_client, mdp_client) VALUES ('Potter', 'Harry', '0607080910', 'harrypotter@client.fr', 'test');
INSERT INTO Client (nom_client, prenom_client, telephone_client, mail_client, mdp_client) VALUES ('Moula', 'Mig', '0678984563', 'migmoula@client.fr', 'test');

INSERT INTO Artisan (id_artisan, nom_artisan, prenom_artisan, nom_boutique) VALUES ('1', 'Tang', 'Enzo', 'Loss Barboss');
INSERT INTO Artisan (id_artisan, nom_artisan, prenom_artisan, nom_boutique) VALUES ('2', 'Givernaud', 'Enzo', 'Chatenay Gang');
INSERT INTO Artisan (id_artisan, nom_artisan, prenom_artisan, nom_boutique) VALUES ('3', 'Geoffroy Pitailler', 'Quentin', 'SDF Company');

INSERT INTO Produit (nom_produit, desc_produit, prix_produit, stock_produit, img_produit_1, img_produit_2, img_produit_3, img_produit_4, id_artisan) VALUES ('Savon Vos Ptits Soins', 'Parce que votre peau est ce qui est de plus important, le savon Vos Ptits Soins nettoie votre peau en profondeur. Mais un savon Vos Ptits Soins va également vous donner une senteur divine jamais ressentie auparavent. Donner à votre peau la liberté de respirer sainement : Le savon idéal pour tous types de peau.', '8', '54', 'savon3.jpg', 'savonjc.png', 'soap-2333412_1280.jpg', 'soap-2726387_1280.jpg', '4');
INSERT INTO Produit (nom_produit, desc_produit, prix_produit, stock_produit, img_produit_1, img_produit_2, img_produit_3, img_produit_4, id_artisan) VALUES ('Mascara Vos Ptits Soins', 'Parce que chaque cil compte, le mascara Vos Ptits Soins démultiplie les cils en les révélant un par un, pour une frange plus étoffée. Un mascara qui sépare les cils un par un, grâce à sa brosse multidimensionnelle. Quand le volume des cils naît de la définition. Chaque fibre de la brosse capte toutes les tailles de cils :  le mascara idéal pour les cils du bas et les petits cils.', '12', '49', 'mascara.jpg', 'mascara2.jpg', 'mascara3.jpg', 'mascara-4.jpg', '5');
INSERT INTO Produit (nom_produit, desc_produit, prix_produit, stock_produit, img_produit_1, img_produit_2, img_produit_3, img_produit_4, id_artisan) VALUES ('Shampoing Vos Ptits Soins', 'Parce que votre peau est ce qui est de plus important, le shampoing Vos Ptits Soins nettoie votre peau en profondeur. Mais un shampoing Vos Ptits Soins va également vous donner une senteur divine jamais ressentie auparavent. Donner à votre peau la liberté de respirer sainement : Le shampoing idéal pour tous types de peau.', '10', '45', 'shampoing5.jpg', 'shampoing2.png', 'shampoing3.jpg', 'savonpack.png', '4');
INSERT INTO Produit (nom_produit, desc_produit, prix_produit, stock_produit, img_produit_1, img_produit_2, img_produit_3, img_produit_4, id_artisan) VALUES ('Masque Vos Ptits Soins', 'Parce que votre peau est ce qui est de plus important, le masque Vos Ptits Soins nettoie votre peau en profondeur. Mais un masque Vos Ptits Soins va également vous donner une douceur divine jamais ressentie auparavent. Donner à votre peau la liberté de respirer sainement : Le masque idéal pour tous types de peau.', '12', '49', 'masque.jpg', 'masque2.jpg', 'masque3.png', 'savonpack.png', '5');
INSERT INTO Produit (nom_produit, desc_produit, prix_produit, stock_produit, img_produit_1, img_produit_2, img_produit_3, img_produit_4, id_artisan) VALUES ('Makeup Vos Ptits Soins', 'Parce que chaque détail compte, le makeup Vos Ptits Soins démultiplie votre beauté en la révélant au grand jour, pour une allure plus féminine. Un makeup qui embellit vos yeux un par un, grâce à sa poudre douce et agréable. Quand la peau naît de la définition. Chaque makeup est naturel :  le makeup idéal pour ltous type de peau.', '30', '22', 'makeup.jpg', 'makeup2.jpg', 'makeup3.jpg', 'makeup4.jpg', '4');
INSERT INTO Produit (nom_produit, desc_produit, prix_produit, stock_produit, img_produit_1, img_produit_2, img_produit_3, img_produit_4, id_artisan) VALUES ('Huile Vos Ptits Soins', 'Parce que votre peau est ce qui est de plus important, une huile Vos Ptits Soins nettoie votre peau en profondeur. Mais une huile Vos Ptits Soins va également vous donner une senteur divine jamais ressentie auparavent. Donner à votre peau la liberté de respirer sainement : une huile idéale pour tous types de peau.', '40', '15', 'huile.png', 'huile2.jpg', 'huile3.jpg', 'huile_pack.png', '5');
INSERT INTO Produit (nom_produit, desc_produit, prix_produit, stock_produit, img_produit_1, img_produit_2, img_produit_3, img_produit_4, id_artisan) VALUES ('Crème Vos Ptits Soins', 'Parce que votre peau est ce qui est de plus important, la crème Vos Ptits Soins nettoie votre peau en profondeur. Mais une crème Vos Ptits Soins va également vous donner une senteur divine jamais ressentie auparavent. Donner à votre peau la liberté de respirer sainement : La crème idéal pour tous types de peau.', '15', '80', 'creme.png', 'creme.jpg', 'cream2.jpg', 'cream6.jpg', '5');
INSERT INTO Produit (nom_produit, desc_produit, prix_produit, stock_produit, img_produit_1, img_produit_2, img_produit_3, img_produit_4, id_artisan) VALUES ('Crème Vos Ptits Soins', 'Parce que votre peau est ce qui est de plus important, la crème Vos Ptits Soins nettoie votre peau en profondeur. Mais une crème Vos Ptits Soins va également vous donner une senteur divine jamais ressentie auparavent. Donner à votre peau la liberté de respirer sainement : La crème idéal pour tous types de peau.', '11', '78', 'creme4.jpg', 'creme3.jpg', 'cremepack.png', 'cream6.jpg', '5');
INSERT INTO Produit (nom_produit, desc_produit, prix_produit, stock_produit, img_produit_1, img_produit_2, img_produit_3, img_produit_4, id_artisan) VALUES ('Crayon Vos Ptits Soins', 'Parce que chaque détail compte, le crayon Vos Ptits Soins démultiplie votre beauté en la révélant au grand jour, pour une allure plus féminine. Un makeup qui embellit vos yeux un par un, grâce à sa mine douce et agréable. Quand la peau naît de la définition. Chaque crayon est naturel :  le crayon idéal pour ltous type de peau.', '5', '45', 'crayon.jpg', 'crayon2.jpg', 'cremepack.png', 'savonpack.png', '4');
INSERT INTO Produit (nom_produit, desc_produit, prix_produit, stock_produit, img_produit_1, img_produit_2, img_produit_3, img_produit_4, id_artisan) VALUES ('Brush Vos Ptits Soins', 'Parce que chaque détail compte, le brush Vos Ptits Soins démultiplie votre beauté en la révélant au grand jour, pour une allure plus féminine. Un brush qui embellit vos yeux un par un, grâce à sa poudre douce et agréable. Quand la peau naît de la définition. Chaque brush est naturel :  le brush idéal pour ltous type de peau.', '18', '64', 'brush.jpg', 'brush3.jpg', 'cremepack.png', 'savonpack.png', '5');




